global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    scrape_interval: 5s
    metrics_path: /prometheus
    static_configs:
      - targets: ['web:8080']